apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-auth
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.n8n.basicAuth.username | b64enc }}
  password: {{ .Values.n8n.basicAuth.password | b64enc }}
  encryptionKey: {{ .Values.n8n.encryptionKey | default (randAlphaNum 32) | b64enc }}
